---
title: "introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(r4msigdb)
```

## Basic usage

This is a basic example which shows you how to query for the MSigDB:

```{r example}
library(r4msigdb)
query(species = 'Hs', pathway = 'FERROPTOSIS') 
query(species = 'Hs', symbols = c('PTPRC', 'TP53')) |> head()
```

You can unlist the symbol column using `.unlist = TRUE`

```{r}
query(species = 'Hs', .unlist = TRUE) |> head()
```

You could query for the MSigDB by your own way if you are familiar with `data.table`

```{r}
query(species = 'Hs')[.('H'), by = .(collection_name)] |> head()
```

## GSEA

```{r message=FALSE}
library(fgsea)
library(data.table)
palette <- c("#440154FF", "#31688EFF", "#26828EFF", "#6DCD59FF", "#FDE725FF")

data(exampleRanks)
pathway <-  query(species = 'Hs', pathway = 'OPTOSIS', .unlist = TRUE)
pathway <- pathway[, .(standard_name, symbol)]
# substitute names with random symbols
set.seed(2024)
names(exampleRanks) <- query(species = 'Hs', .unlist = TRUE)[, sample(unique(symbol), length(exampleRanks))]

gseaR <- clusterProfiler::GSEA(rev(exampleRanks),
  TERM2GENE = pathway, pvalueCutoff = 1, by = "fgsea", eps = 0
)
sortedgsea <- as.data.table(gseaR@result)[order(pvalue)]

enrichplot::gseaplot2(gseaR, sortedgsea[["ID"]][1:5],
  base_size = 10,
  color = palette,
  rel_heights = c(1.5, 0.3, 0.5),
  pvalue_table = FALSE
)
```
